name: Build & deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest      

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Build
      run: |
        npm install
        grunt
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: "./build"
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
